### PR TITLE
Issue/4 draw mockups

### LINKED ISSUE #4: Draw mockups

### PR DESCRIPTION
**Pull request by carina-str**
closes #4

### CODE REVIEW

**Review by diehmlukas — CHANGES_REQUESTED** [review]
Please remove the file local.properties from the pull request.
That the local.properties automatically check in, is a bug who is fixed when Marcel merging the branch issue/20-config.

**Review by mac641 — CHANGES_REQUESTED** [review]
I've wrote some comments requesting minor changes. I'd love to see them addressed 😅

Regarding formatting stuff, I recommend running `flutter format lib/ test/` before committing ^^

Regarding folder structure, I was thinking, we could create a package for each part of the app.
For example our `lib/` folder could look like this:

```
+ project root
|
+-- lib
       +-- config
       +-- ui
       +-- notifications
...
```
Let me know your thoughts about this 😁

**Comment by AnnaGsell** [comment]
I noticed that some commit messages are missing the '-' between the issue number and the message text. You could adjust them with `git rebase -i` and choosing the `reword` option. But I don't think it's a blocker for merging this PR ;)

**Review by mac641 — APPROVED** [review]
Looks good 👍🏿
Can't complain 😅

**Review by diehmlukas — APPROVED** [review]
looks good =)

**Pull request merged**
