### PR TITLE
Issue/66 app loading screen

### LINKED ISSUE #23: Implement reaction games
needs #54
needs #55
needs #56
needs #57

### LINKED ISSUE #54: Implement cognitive fatigue self-assessment

### LINKED ISSUE #56: Implement PVT

### LINKED ISSUE #66: Style app loading screen
This issue refers to `// TODO: style CircularProgressIndicator appropriately` in main.dart

### PR DESCRIPTION
**Pull request by carina-str**
closes #66
closes #54
closes #56
closes #23 
closes #75
closes #76

### CODE REVIEW

**Review by mac641 — CHANGES_REQUESTED** [review]
Looks really good, clean and plausible to me 😁
Just some minor improvement suggestions, I've noticed 😅

**Review by mac641 — DISMISSED** [review]
Sick 😷😁

**Review by diehmlukas — APPROVED** [review]

**Review by diehmlukas — APPROVED** [review]
:+1:

**Review by mac641 — APPROVED** [review]
👍🏿

**Pull request merged**
