### PR TITLE
Issue/72 - Remove moods from config

### LINKED ISSUE #72: Remove mood smileys from config

### LINKED ISSUE #82: Adjust app frontend
to be storing `currentActivity` as List<int> containing code units instead of storing them as strings

### PR DESCRIPTION
**Pull request by mac641**
closes #72 
closes #82 

Also make `currentActivity` be stored as `List<int>` instead of `String`.

### CODE REVIEW

**Review by diehmlukas — DISMISSED** [review]
Looks good :+1:

**Review by diehmlukas — APPROVED** [review]

**Comment by mac641** [comment]
closes #82

**Review by carina-str — APPROVED** [review]
Looks fine for me 😊

**Review by diehmlukas — APPROVED** [review]
I like it....




....again :+1:

**Pull request merged**
