### PR TITLE
Issue/49 - Improve flutter analyze rules

### LINKED ISSUE #49: Adjust flutter analyze rules
* formatting stuff is recognized in a more unifying way
* variable and file naming differences are detected

### PR DESCRIPTION
**Pull request by mac641**
closes #49

### CODE REVIEW

**Comment by mac641** [comment]
Dart linter rules are explained [here](https://dart-lang.github.io/linter/lints/index.html)

**Review by AnnaGsell — COMMENTED** [review]
looks good to me :)

**Review by diehmlukas — APPROVED** [review]
I think we'll swear about it for a while, but otherwise it looks good for me. =)

**Review by carina-str — APPROVED** [review]
Looks good :)

**Pull request merged**
